version: "3"

services:
  my_server:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www/
    container_name: project_nginx
    depends_on:
      - my_app

#  my_lang:
#    image: php:8.0-fpm
#    volumes:
#      - ./:/var/www/
#    container_name: project_lang
  my_app:
      build:
          context: .
          dockerfile: _docker/app/Dockerfile
      volumes:
        - ./:/var/www/
      container_name: project_app
      depends_on:
          - my_db

  my_db:
      image: mysql:8.0
      volumes:
          - ./tmp/db/:/var/lib/mysql/
      restart: always
      container_name: project_db
      environment:
          - MYSQL_DATABASE=my_laravel
          - MYSQL_ROOT_PASSWORD=root
      command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
      ports:
          - 8877:3306
